In [1]:
import seaborn as sns
import numpy as np
import pandas as pd  
import matplotlib.pyplot as plt

In [2]:
df=pd.read_excel('Hospital_data.xlsx')
print(df)

      Encounter ID Patient ID          Facility              Dept  \
0       ENC-000001   PT-14706     West Hospital         Emergency
1       ENC-000002   PT-24777     East Hospital  General Medicine
2       ENC-000003   PT-15738     West Hospital       Orthopedics
3       ENC-000004   PT-20541  Central Hospital               ICU
4       ENC-000005   PT-05720     East Hospital         Emergency
...            ...        ...               ...               ...
99995   ENC-099996   PT-10567     East Hospital  General Medicine
99996   ENC-099997   PT-22677     West Hospital               ICU
99997   ENC-099998   PT-06673     East Hospital       Orthopedics
99998   ENC-099999   PT-02784     East Hospital               ICU
99999   ENC-100000   PT-14217  Central Hospital           Surgery

                         Arrival                     Triage  \
0               2026-01-25 02:20           2026-01-25 03:10
1               28/07/2026 23:14           28/07/2026 23:55
2           2026-06-26T17:37:00Z       2026-06-26T17:54:00Z
3               2026/04/29 11:55           2026/04/29 12:41
4      2026-04-27T21:56:00+05:30  2026-04-27T21:32:00+05:30
...                          ...                        ...
99995           2026-06-15 10:04           2026-06-15 10:54
99996           03/09/2026 04:32           03/09/2026 05:36
99997       2026-02-08T00:23:00Z       2026-02-08T00:49:00Z
99998           2026/03/07 23:09           2026/03/08 00:13
99999  2026-05-23T07:05:00+05:30  2026-05-23T08:12:00+05:30

                       Discharge       Status Lab Unit Appointment ID  ...  \
0               2026-01-25 07:39     COMPLETE      NaN    APT-0000001  ...
1               29/07/2026 06:38   Discharged   mmol/L    APT-0000002  ...
2           2026-06-26T22:18:00Z     Admitted    mg/dL    APT-0000003  ...
3               2026/04/29 21:28      No-show    mg/dL    APT-0000004  ...
4      2026-04-28T00:56:00+05:30    Completed      NaN    APT-0000005  ...
...                          ...          ...      ...            ...  ...
99995           2026-06-15 16:04   Discharged     g/dL    APT-0099996  ...
99996           03/09/2026 08:08  In Progress   mmol/l    APT-0099997  ...
99997       2026-02-08T06:57:00Z  In Progress   10^9/L    APT-0099998  ...
99998           2026/03/08 10:08    Cancelled   10^9/L    APT-0099999  ...
99999  2026-05-23T15:37:00+05:30   completed     MG/DL    APT-0100000  ...

      Paid Amount Outstanding Amount  Staff Shift Shift Start Shift End  \
0       106932.95            -670.46  night shift       22:00     06:00
1        72324.21           16513.51      Evening        7 AM      6 AM
2        37339.91           -3196.40  22:00-06:00       07:00     06:00
3         7984.16           72830.70  22:00-06:00       08:00      6 AM
4        25539.58           47763.16          NaN         NaN     23:00
...           ...                ...          ...         ...       ...
99995     2063.47            1984.59      Evening       15:00       NaN
99996    57488.60           71299.95  22:00-06:00       07:00     06:00
99997    25814.07           27221.14      Evening        7 AM       NaN
99998   132480.11           11370.93          Day       07:00      6 AM
99999    40986.79           15163.26  22:00-06:00         NaN      6 AM

       Severity Priority    Patient Name           Phone  \
0        URGENT  routine  Patient_957524  +91-9209530557
1      Moderate     STAT  Patient_620749  +91-6465408257
2        URGENT     High  Patient_472068  +91-6214669636
3      Moderate     STAT  Patient_268653  +91-9417619224
4      Critical  Routine  Patient_166595  +91-9097105491
...         ...      ...             ...             ...
99995      High       P1  Patient_923956  +91-8602856532
99996       Low     STAT  Patient_657185  +91-7909440847
99997    URGENT       P1  Patient_297923  +91-7832088409
99998    URGENT       P1  Patient_782076  +91-9462567198
99999    URGENT     STAT  Patient_633697  +91-7093174396

                               Clinical Notes
0      Confidential: patient details recorded
1                          Routine assessment
2                          Routine assessment
3                          Follow-up required
4                          Routine assessment
...                                       ...
99995                   Patient reported pain
99996  Confidential: patient details recorded
99997  Confidential: patient details recorded
99998  Confidential: patient details recorded
99999                      Discharge planning

[100000 rows x 46 columns]

In [3]:
#Q1Trim and standardize patient, encounter, appointment, and order IDs; map aliases using approved master tables.
# Columns containing IDs
id_columns = ["Patient ID", "Encounter ID", "Appointment ID", "Lab Order ID"]

# Trim spaces and convert IDs to uppercase
for col in id_columns:
    df[col] = df[col].astype("string").str.strip().str.upper()

# Display the cleaned IDs
print(df[id_columns].head(10))

  Patient ID Encounter ID Appointment ID Lab Order ID
0   PT-14706   ENC-000001    APT-0000001  LAB-0000001
1   PT-24777   ENC-000002    APT-0000002  LAB-0000002
2   PT-15738   ENC-000003    APT-0000003  LAB-0000003
3   PT-20541   ENC-000004    APT-0000004  LAB-0000004
4   PT-05720   ENC-000005    APT-0000005  LAB-0000005
5   PT-05861   ENC-000006    APT-0000006  LAB-0000006
6   PT-09384   ENC-000007    APT-0000007  LAB-0000007
7   PT-08581   ENC-000008    APT-0000008  LAB-0000008
8   PT-10940   ENC-000009    APT-0000009  LAB-0000009
9   PT-04731   ENC-000010    APT-0000010  LAB-0000010

In [4]:
#2. Replace direct patient identifiers in analytics extracts with a consistent pseudonymous key.
# Create a pseudonymous patient key
df["Patient_Key"] = df["Patient ID"].astype("string").str.strip().str.upper()
# Display the output
print(df[["Patient_Key", "Encounter ID", "Facility", "Dept"]].head(10))

  Patient_Key Encounter ID          Facility              Dept
0    PT-14706   ENC-000001     West Hospital         Emergency
1    PT-24777   ENC-000002     East Hospital  General Medicine
2    PT-15738   ENC-000003     West Hospital       Orthopedics
3    PT-20541   ENC-000004  Central Hospital               ICU
4    PT-05720   ENC-000005     East Hospital         Emergency
5    PT-05861   ENC-000006  Central Hospital        Cardiology
6    PT-09384   ENC-000007     East Hospital       Orthopedics
7    PT-08581   ENC-000008     West Hospital        Laboratory
8    PT-10940   ENC-000009     East Hospital               ICU
9    PT-04731   ENC-000010    North Hospital               ICU

In [5]:
#3. Parse timestamps and normalize them to the facility's documented timezone or UTC.
time_columns = ["Arrival", "Triage", "Discharge", "Appointment DateTime",
                "Admission", "Transfer", "Procedure DateTime",
                "Lab Result DateTime", "Shift Start", "Shift End"]

for col in time_columns:
    df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)
df[time_columns].head(10)

C:\Users\subhashis\AppData\Local\Temp\ipykernel_28524\4210225794.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)
C:\Users\subhashis\AppData\Local\Temp\ipykernel_28524\4210225794.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)

,Arrival,Triage,Discharge,Appointment DateTime,Admission,Transfer,Procedure DateTime,Lab Result DateTime,Shift Start,Shift End
0,2026-01-25 02:20:00+00:00,2026-01-25 03:10:00+00:00,2026-01-25 07:39:00+00:00,2026-01-11 11:01:00+00:00,2026-01-25 02:48:00+00:00,2026-01-25 06:57:00+00:00,2026-01-25 05:35:00+00:00,2026-01-25 09:23:00+00:00,2026-10-26 22:00:00+00:00,2026-10-26 06:00:00+00:00
1,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
2,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2026-10-26 07:00:00+00:00,2026-10-26 06:00:00+00:00
3,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2026-10-26 08:00:00+00:00,NaT
4,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2026-10-26 23:00:00+00:00
5,2026-08-20 19:42:00+00:00,2026-08-20 20:02:00+00:00,2026-08-21 04:36:00+00:00,2026-08-20 05:01:00+00:00,2026-08-20 19:56:00+00:00,2026-08-21 01:13:00+00:00,2026-08-20 22:05:00+00:00,2026-08-21 00:00:00+00:00,2026-10-26 07:00:00+00:00,NaT
6,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT
7,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2026-10-26 07:00:00+00:00,2026-10-26 15:00:00+00:00
8,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2026-10-26 07:00:00+00:00,2026-10-26 16:00:00+00:00
9,NaT,NaT,NaT,NaT,NaT,NaT,NaT,NaT,2026-10-26 22:00:00+00:00,2026-10-26 15:00:00+00:00

In [6]:
#4. Standardize facility, ward, department, specialty, and clinician role names using reference lists.
mappings = {
    "Facility": {
        "NORTH HOSP": "NORTH-HOSPITAL",
        "NORTH HOSPITAL": "NORTH-HOSPITAL",
        "SOUTH HOSPITAL": "SOUTH-HOSPITAL"
    },
    "Ward": {
        "ER WARD": "EMERGENCY WARD",
        "ICU-1": "ICU"
    },
    "Dept": {
        "ER": "EMERGENCY",
        "CARDIO": "CARDIOLOGY",
        "LAB": "LABORATORY"
    },
    "Specialty": {
        "CARDIO": "CARDIOLOGY",
        "PEDS": "PEDIATRICS"
    },
    "Clinician Role": {
        "MD": "PHYSICIAN",
        "DOCTOR": "PHYSICIAN"
    }
}

columns = ["Facility", "Ward", "Dept", "Specialty", "Clinician Role"]

for col in columns:
    df[col] = df[col].astype("string").str.strip().str.upper()
    df[col] = df[col].replace(mappings[col])

df[columns].head(10)

,Facility,Ward,Dept,Specialty,Clinician Role
0,WEST HOSPITAL,EMERGENCY WARD,EMERGENCY,PATHOLOGY,CONSULTANT
1,EAST HOSPITAL,GENERAL WARD,GENERAL MEDICINE,CARDIOLOGY,RESIDENT
2,WEST HOSPITAL,GENERAL WARD,ORTHOPEDICS,PEDIATRICS,TECHNICIAN
3,CENTRAL HOSPITAL,CARDIOLOGY WARD,ICU,EMERGENCY MEDICINE,NURSE
4,EAST HOSPITAL,ICU,EMERGENCY,ORTHOPEDICS,RESIDENT
5,CENTRAL HOSPITAL,GENERAL WARD,CARDIOLOGY,INTERNAL MEDICINE,REGISTRAR
6,EAST HOSPITAL,GENERAL WARD,ORTHOPEDICS,INTERNAL MEDICINE,REGISTRAR
7,WEST HOSPITAL,PEDIATRIC WARD,LABORATORY,ORTHOPEDICS,TECHNICIAN
8,EAST HOSPITAL,PEDIATRIC WARD,ICU,PATHOLOGY,RESIDENT
9,NORTH-HOSPITAL,SURGICAL WARD,ICU,PEDIATRICS,CONSULTANT

In [7]:
#5. Normalize appointment and encounter statuses (scheduled, arrived, completed, cancelled, no-show).
status_mapping = {
    "scheduled": "SCHEDULED",
    "arrived": "ARRIVED",
    "completed": "COMPLETED",
    "complete": "COMPLETED",
    "done": "COMPLETED",
    "cancelled": "CANCELLED",
    "canceled": "CANCELLED",
    "no-show": "NO-SHOW",
    "no show": "NO-SHOW"
}

for col in ["Status", "Appointment Status"]:
    if col in df.columns:
        df[col] = df[col].astype("string").str.strip().str.lower()
        df[col] = df[col].replace(status_mapping)

df[["Status", "Appointment Status"]].head(10)

        Status Appointment Status
0    COMPLETED            ARRIVED
1   discharged            NO-SHOW
2     admitted            ARRIVED
3      NO-SHOW          COMPLETED
4    COMPLETED          COMPLETED
5   discharged            NO-SHOW
6    CANCELLED          SCHEDULED
7  in progress          CANCELLED
8    CANCELLED          COMPLETED
9    COMPLETED          SCHEDULED

In [8]:
#6. Validate admission, transfer, procedure, and discharge event ordering; flag impossible sequences.
columns = ["Admission", "Transfer", "Procedure DateTime", "Discharge"]

for col in columns:
    df[col] = pd.to_datetime(df[col], errors="coerce", utc=True)

df["Event Order Issue"] = (
    (df["Admission"].notna() & df["Transfer"].notna() & (df["Transfer"] < df["Admission"])) |
    (df["Admission"].notna() & df["Procedure DateTime"].notna() & (df["Procedure DateTime"] < df["Admission"])) |
    (df["Admission"].notna() & df["Discharge"].notna() & (df["Discharge"] < df["Admission"])) |
    (df["Transfer"].notna() & df["Discharge"].notna() & (df["Discharge"] < df["Transfer"])) |
    (df["Procedure DateTime"].notna() & df["Discharge"].notna() & (df["Discharge"] < df["Procedure DateTime"]))
)

df[columns + ["Event Order Issue"]].head(10)

,Admission,Transfer,Procedure DateTime,Discharge,Event Order Issue
0,2026-01-25 02:48:00+00:00,2026-01-25 06:57:00+00:00,2026-01-25 05:35:00+00:00,2026-01-25 07:39:00+00:00,False
1,NaT,NaT,NaT,NaT,False
2,NaT,NaT,NaT,NaT,False
3,NaT,NaT,NaT,NaT,False
4,NaT,NaT,NaT,NaT,False
5,2026-08-20 19:56:00+00:00,2026-08-21 01:13:00+00:00,2026-08-20 22:05:00+00:00,2026-08-21 04:36:00+00:00,False
6,NaT,NaT,NaT,NaT,False
7,NaT,NaT,NaT,NaT,False
8,NaT,NaT,NaT,NaT,False
9,NaT,NaT,NaT,NaT,False

In [9]:
#7. Normalize laboratory test names, specimen types, result units, and reference-range metadata using a catalogue.
lab_mapping = {
    "Lab Test": {"CBC": "COMPLETE BLOOD COUNT"},
    "Specimen Type": {"BLOOD": "Blood", "blood": "Blood"},
    "Lab Result Unit": {"MG/DL": "mg/dL", "MMOL/L": "mmol/L", "G/DL": "g/dL", "U/L": "U/L"},
    "Reference Range": {"NOT_APPLICABLE": None, "NOT APPLICABLE": None}
}

for col, mapping in lab_mapping.items():
    df[col] = df[col].astype("string").str.strip().replace(mapping)

df[["Lab Test", "Specimen Type", "Lab Result Unit", "Reference Range"]].head(10)

               Lab Test Specimen Type Lab Result Unit Reference Range
0               Glucose          Swab            <NA>   0.6-1.2 mg/dL
1             Potassium         Blood          mmol/L            None
2           Lipid Panel         Blood           mg/dL            None
3  COMPLETE BLOOD COUNT         Serum           mg/dL   0.6-1.2 mg/dL
4                   WBC        Plasma            <NA>   0.6-1.2 mg/dL
5                   ALT          Swab           mg/dL    70-100 mg/dL
6                   AST         Urine            <NA>            None
7            Hemoglobin         Blood           mg/dL  135-145 mmol/L
8            Creatinine          Swab           mg/dL   0.6-1.2 mg/dL
9           Lipid Panel         Urine          mmol/l   0.6-1.2 mg/dL

In [10]:
#8. Convert compatible measurement units only when the source unit and conversion rule are known.
# Standardize the format of lab result units
df["Lab Result Unit"] = df["Lab Result Unit"].astype("string").str.strip()

df["Lab Result Unit"] = df["Lab Result Unit"].replace({
    "mmol/l": "mmol/L",
    "MMOL/L": "mmol/L",
    "MG/DL": "mg/dL",
    "G/DL": "g/dL"
})

# Display the standardized units
df["Lab Result Unit"].value_counts()

Lab Result Unit
mg/dL     24948
mmol/L    24869
U/L       12534
10^9/L    12482
g/dL      12414
Name: count, dtype: Int64

In [11]:
#9. Standardize diagnosis and procedure codes to the specified coding-system version; flag invalid codes.
# Clean diagnosis and procedure codes
for col in ["Diagnosis Code", "Procedure Code"]:
    df[col] = df[col].astype("string").str.strip().str.upper()

    df[col + " Issue"] = (
        df[col].isna() |
        df[col].isin(["", "INVALID_CODE", "PROC-X", "NOT_APPLICABLE"])
    )

# Display the results
print(df[["Diagnosis Code", "Diagnosis Code Issue",
          "Procedure Code", "Procedure Code Issue"]].head(10))

  Diagnosis Code  Diagnosis Code Issue Procedure Code  Procedure Code Issue
0            I10                 False         PROC-X                  True
1   INVALID_CODE                  True          99213                 False
2          J18.9                 False          93000                 False
3          Z00.0                 False         PROC-X                  True
4            I10                 False          93000                 False
5            I10                 False         PROC-X                  True
6          Z00.0                 False          99213                 False
7          Z00.0                 False          99213                 False
8          E11.9                 False          99213                 False
9          E11.9                 False          99213                 False

In [12]:
#10. Normalize medication administration status and dosage units; do not infer missing clinical values.
# Standardize medication administration status
df["Medication Administration Status"] = (
    df["Medication Administration Status"]
    .astype("string")
    .str.strip()
    .str.lower()
    .replace({
        "administered": "ADMINISTERED",
        "not administered": "NOT ADMINISTERED",
        "missed": "MISSED",
        "held": "HELD"
    })
)

# Standardize dosage unit format
df["Dosage Unit"] = (
    df["Dosage Unit"]
    .astype("string")
    .str.strip()
    .replace({
        "MG": "mg",
        "MCG": "mcg",
        "ML": "mL",
        "G": "g",
        "UNITS": "units"
    })
)

# Display the results
print(df[["Medication Administration Status", "Dosage Unit"]].head(10))

  Medication Administration Status Dosage Unit
0                     ADMINISTERED       units
1                     ADMINISTERED       units
2                           MISSED       units
3                           MISSED       units
4                     ADMINISTERED       units
5                             HELD          mg
6                             HELD          mL
7                     ADMINISTERED         mcg
8                             HELD         mcg
9                             <NA>          mL

In [13]:
#11. Deduplicate repeated appointment, lab, and bed-movement events using event keys and source priority.
# Remove duplicate appointment events
df = df.drop_duplicates(
    subset=["Appointment ID", "Patient ID", "Appointment DateTime"],
    keep="first"
)

# Remove duplicate lab events
df = df.drop_duplicates(
    subset=["Lab Order ID", "Encounter ID", "Lab Test", "Lab Result DateTime"],
    keep="first"
)

# Display the results
print("Records remaining after deduplication:", len(df))
print(df[["Appointment ID", "Lab Order ID", "Bed ID"]].head(10))

Records remaining after deduplication: 100000
  Appointment ID Lab Order ID    Bed ID
0    APT-0000001  LAB-0000001  BED-0492
1    APT-0000002  LAB-0000002  BED-1072
2    APT-0000003  LAB-0000003  BED-0597
3    APT-0000004  LAB-0000004  BED-1660
4    APT-0000005  LAB-0000005  BED-0017
5    APT-0000006  LAB-0000006  BED-1131
6    APT-0000007  LAB-0000007  BED-0530
7    APT-0000008  LAB-0000008  BED-1135
8    APT-0000009  LAB-0000009  BED-0388
9    APT-0000010  LAB-0000010  BED-0283

In [14]:
#12. Validate bed, ward, and facility identifiers against the bed inventory.
# Check for missing bed, ward, and facility information
for col in ["Bed ID", "Ward", "Facility"]:
    df[col] = df[col].astype("string").str.strip()

df["Bed Information Issue"] = (
    df["Bed ID"].isna() | (df["Bed ID"] == "") |
    df["Ward"].isna() | (df["Ward"] == "") |
    df["Facility"].isna() | (df["Facility"] == "")
)

# Display the results
print(df[["Bed ID", "Ward", "Facility", "Bed Information Issue"]].head(10))

     Bed ID             Ward          Facility  Bed Information Issue
0  BED-0492   EMERGENCY WARD     WEST HOSPITAL                  False
1  BED-1072     GENERAL WARD     EAST HOSPITAL                  False
2  BED-0597     GENERAL WARD     WEST HOSPITAL                  False
3  BED-1660  CARDIOLOGY WARD  CENTRAL HOSPITAL                  False
4  BED-0017              ICU     EAST HOSPITAL                  False
5  BED-1131     GENERAL WARD  CENTRAL HOSPITAL                  False
6  BED-0530     GENERAL WARD     EAST HOSPITAL                  False
7  BED-1135   PEDIATRIC WARD     WEST HOSPITAL                  False
8  BED-0388   PEDIATRIC WARD     EAST HOSPITAL                  False
9  BED-0283    SURGICAL WARD    NORTH-HOSPITAL                  False

In [15]:
#13. Standardize payer and billing categories; parse billed, paid, and outstanding amounts as decimals.
# Standardize payer names
df["Payer"] = df["Payer"].astype("string").str.strip().str.upper()

df["Payer"] = df["Payer"].replace({
    "SELF PAY": "SELF-PAY",
    "SELF-PAY": "SELF-PAY",
    "GOVT": "GOVERNMENT"
})

# Convert billing amounts to decimal numbers
amount_columns = ["Billed Amount", "Paid Amount", "Outstanding Amount"]

for col in amount_columns:
    df[col] = pd.to_numeric(df[col], errors="coerce").astype("float64")

# Display the results
print(df[["Payer"] + amount_columns].head(10))

               Payer  Billed Amount  Paid Amount  Outstanding Amount
0          CORPORATE      106262.49    106932.95             -670.46
1         GOVERNMENT       88837.72     72324.21            16513.51
2           SELF-PAY       34143.51     37339.91            -3196.40
3         GOVERNMENT       80814.86      7984.16            72830.70
4           SELF-PAY       73302.74     25539.58            47763.16
5  PRIVATE INSURANCE      139738.53     99801.86            39936.67
6          CORPORATE      106851.06     66491.24            40359.82
7         GOVERNMENT       55364.36     30275.62            25088.74
8           SELF-PAY       23122.61      9271.70            13850.91
9           SELF-PAY       26192.32       108.29            26084.03

In [16]:
#14. Normalize staff shift labels and date boundaries for overnight shifts.
# Standardize staff shift labels
df["Staff Shift"] = df["Staff Shift"].astype("string").str.strip().str.upper()

df["Staff Shift"] = df["Staff Shift"].replace({
    "NIGHT SHIFT": "NIGHT",
    "NIGHT-SHIFT": "NIGHT",
    "DAY SHIFT": "DAY",
    "DAY-SHIFT": "DAY"
})

# Convert shift start and end times
df["Shift Start"] = pd.to_datetime(df["Shift Start"], format="mixed", errors="coerce")
df["Shift End"] = pd.to_datetime(df["Shift End"], format="mixed", errors="coerce")

# Move the end time to the next day for overnight shifts
df.loc[df["Shift End"] < df["Shift Start"], "Shift End"] += pd.Timedelta(days=1)

# Display the results
df[["Staff Shift", "Shift Start", "Shift End"]].head(10)

   Staff Shift               Shift Start                 Shift End
0        NIGHT 2026-10-26 22:00:00+00:00 2026-10-27 06:00:00+00:00
1      EVENING                       NaT                       NaT
2  22:00-06:00 2026-10-26 07:00:00+00:00 2026-10-27 06:00:00+00:00
3  22:00-06:00 2026-10-26 08:00:00+00:00                       NaT
4         <NA>                       NaT 2026-10-26 23:00:00+00:00
5        NIGHT 2026-10-26 07:00:00+00:00                       NaT
6        NIGHT                       NaT                       NaT
7        NIGHT 2026-10-26 07:00:00+00:00 2026-10-26 15:00:00+00:00
8        NIGHT 2026-10-26 07:00:00+00:00 2026-10-26 16:00:00+00:00
9         <NA> 2026-10-26 22:00:00+00:00 2026-10-27 15:00:00+00:00

In [17]:
#15. Handle missing arrival, triage, or discharge timestamps using explicit null rules rather than fabricated values.
# Flag records with missing timestamps
df["Timestamp Issue"] = ""

df.loc[df["Arrival"].isna(), "Timestamp Issue"] = "Missing Arrival"
df.loc[df["Triage"].isna(), "Timestamp Issue"] += " Missing Triage"
df.loc[df["Discharge"].isna(), "Timestamp Issue"] += " Missing Discharge"

# Display the results
print(df[["Status", "Arrival", "Triage", "Discharge", "Timestamp Issue"]].head(10))

print("Records requiring timestamp review:", (df["Timestamp Issue"] != "").sum())

        Status                   Arrival                    Triage  \
0    COMPLETED 2026-01-25 02:20:00+00:00 2026-01-25 03:10:00+00:00
1   discharged                       NaT                       NaT
2     admitted                       NaT                       NaT
3      NO-SHOW                       NaT                       NaT
4    COMPLETED                       NaT                       NaT
5   discharged 2026-08-20 19:42:00+00:00 2026-08-20 20:02:00+00:00
6    CANCELLED                       NaT                       NaT
7  in progress                       NaT                       NaT
8    CANCELLED                       NaT                       NaT
9    COMPLETED                       NaT                       NaT

                  Discharge                                   Timestamp Issue
0 2026-01-25 07:39:00+00:00
1                       NaT  Missing Arrival Missing Triage Missing Discharge
2                       NaT  Missing Arrival Missing Triage Missing Discharge
3                       NaT  Missing Arrival Missing Triage Missing Discharge
4                       NaT  Missing Arrival Missing Triage Missing Discharge
5 2026-08-21 04:36:00+00:00
6                       NaT  Missing Arrival Missing Triage Missing Discharge
7                       NaT  Missing Arrival Missing Triage Missing Discharge
8                       NaT  Missing Arrival Missing Triage Missing Discharge
9                       NaT  Missing Arrival Missing Triage Missing Discharge
Records requiring timestamp review: 80000

In [ ]:
#16. Flag negative wait durations, discharge before admission, and lab results before specimen collection.
#Flag negative wait durations (Triage before Arrival)
df["Negative Wait"] = (
    df["Arrival"].notna() &
    df["Triage"].notna() &
    (df["Triage"] < df["Arrival"])
)

#Flag discharge before admission
df["Discharge Before Admission"] = (
    df["Admission"].notna() &
    df["Discharge"].notna() &
    (df["Discharge"] < df["Admission"])
)

#Display flagged records
print("Records with Negative Wait:")
print(df[df["Negative Wait"]][["Encounter ID", "Arrival", "Triage"]].head(10))

print("\nRecords with Discharge Before Admission:")
print(df[df["Discharge Before Admission"]][["Encounter ID", "Admission", "Discharge"]].head(10))

# Display counts
print("\nTotal negative wait records:", df["Negative Wait"].sum())
print("Total discharge-before-admission records:", df["Discharge Before Admission"].sum())

print("\nNote: Lab result vs. specimen collection cannot be checked because a separate specimen collection timestamp is not available.")

Records with Negative Wait:
     Encounter ID                   Arrival                    Triage
145    ENC-000146 2026-08-19 10:03:00+00:00 2026-08-19 09:52:00+00:00
180    ENC-000181 2026-09-11 06:34:00+00:00 2026-09-11 06:09:00+00:00
450    ENC-000451 2026-09-17 06:38:00+00:00 2026-09-17 06:27:00+00:00
665    ENC-000666 2026-07-07 14:17:00+00:00 2026-07-07 14:12:00+00:00
790    ENC-000791 2026-01-26 19:59:00+00:00 2026-01-26 19:50:00+00:00
935    ENC-000936 2026-09-11 23:03:00+00:00 2026-09-11 22:37:00+00:00
1260   ENC-001261 2026-03-13 20:18:00+00:00 2026-03-13 19:52:00+00:00
1305   ENC-001306 2026-07-01 08:03:00+00:00 2026-07-01 07:38:00+00:00
1330   ENC-001331 2026-05-02 11:01:00+00:00 2026-05-02 10:35:00+00:00
1405   ENC-001406 2026-02-11 23:15:00+00:00 2026-02-11 22:54:00+00:00

Records with Discharge Before Admission:
    Encounter ID                 Admission                 Discharge
100   ENC-000101 2026-08-13 22:11:00+00:00 2026-08-13 21:59:00+00:00
230   ENC-000231 2026-05-06 03:35:00+00:00 2026-05-06 02:58:00+00:00
370   ENC-000371 2026-04-01 16:15:00+00:00 2026-04-01 15:40:00+00:00
465   ENC-000466 2026-09-18 23:33:00+00:00 2026-09-18 22:31:00+00:00
480   ENC-000480 2026-03-19 20:44:00+00:00 2026-03-19 20:41:00+00:00
500   ENC-000501 2026-01-31 19:09:00+00:00 2026-01-31 19:06:00+00:00
540   ENC-000541 2026-07-11 11:57:00+00:00 2026-07-11 11:36:00+00:00
545   ENC-000546 2026-01-15 12:48:00+00:00 2026-01-15 11:28:00+00:00
645   ENC-000646 2026-03-30 18:19:00+00:00 2026-03-30 15:37:00+00:00
680   ENC-000681 2026-07-15 10:23:00+00:00 2026-07-15 09:45:00+00:00

Total negative wait records: 472
Total discharge-before-admission records: 1531

Note: Lab result vs. specimen collection cannot be checked because a separate specimen collection timestamp is not available.

In [19]:
#17. Separate test records and cancelled encounters from operational denominators using documented criteria.
# Identify cancelled encounters
df["Cancelled Encounter"] = (
    df["Status"].astype("string").str.strip().str.upper() == "CANCELLED"
)

# Identify possible test records using Clinical Notes
df["Test Record"] = (
    df["Clinical Notes"].astype("string").str.strip().str.upper()
    .str.contains("TEST", na=False)
)

# Identify records included in operational calculations
df["Include in Operations"] = (
    ~df["Cancelled Encounter"] & ~df["Test Record"]
)

# Display the results
print(df[["Encounter ID", "Status", "Clinical Notes",
          "Cancelled Encounter", "Test Record",
          "Include in Operations"]].head(10))

print("\nCancelled encounters:", df["Cancelled Encounter"].sum())
print("Possible test records:", df["Test Record"].sum())
print("Records included in operations:", df["Include in Operations"].sum())

  Encounter ID       Status                          Clinical Notes  \
0   ENC-000001    COMPLETED  Confidential: patient details recorded
1   ENC-000002   discharged                      Routine assessment
2   ENC-000003     admitted                      Routine assessment
3   ENC-000004      NO-SHOW                      Follow-up required
4   ENC-000005    COMPLETED                      Routine assessment
5   ENC-000006   discharged                      Discharge planning
6   ENC-000007    CANCELLED                      Follow-up required
7   ENC-000008  in progress                      Follow-up required
8   ENC-000009    CANCELLED  Confidential: patient details recorded
9   ENC-000010    COMPLETED                      Discharge planning

   Cancelled Encounter  Test Record  Include in Operations
0                False        False                   True
1                False        False                   True
2                False        False                   True
3                False        False                   True
4                False        False                   True
5                False        False                   True
6                 True        False                  False
7                False        False                   True
8                 True        False                  False
9                False        False                   True

Cancelled encounters: 12548
Possible test records: 0
Records included in operations: 87452

In [20]:
#18. Normalize severity and priority labels only according to approved mapping tables.
# Clean Severity and Priority labels
for col in ["Severity", "Priority"]:
    df[col] = df[col].astype("string").str.strip().str.upper()

# Display the results
print(df[["Severity", "Priority"]].head(10))

# Show all unique labels
print("\nSeverity labels:", df["Severity"].unique())
print("Priority labels:", df["Priority"].unique())

   Severity Priority
0    URGENT  ROUTINE
1  MODERATE     STAT
2    URGENT     HIGH
3  MODERATE     STAT
4  CRITICAL  ROUTINE
5      HIGH     STAT
6    URGENT   URGENT
7       LOW  ROUTINE
8    URGENT     STAT
9       LOW   URGENT

Severity labels: <StringArray>
['URGENT', 'MODERATE', 'CRITICAL', 'HIGH', 'LOW']
Length: 5, dtype: string
Priority labels: <StringArray>
['ROUTINE', 'STAT', 'HIGH', 'URGENT', 'P1']
Length: 5, dtype: string

In [21]:
#19. Link lab orders and results using encounter/order keys and identify orphan results.
# Check for missing lab order or encounter IDs
df["Orphan Lab Result"] = (
    df["Lab Order ID"].isna() |
    df["Encounter ID"].isna() |
    df["Lab Order ID"].astype("string").str.strip().isin(["", "NOT_APPLICABLE"]) |
    df["Encounter ID"].astype("string").str.strip().isin(["", "NOT_APPLICABLE"])
)

# Check lab orders linked to multiple encounters
order_links = df.groupby("Lab Order ID")["Encounter ID"].nunique()
invalid_orders = order_links[order_links > 1]

# Display the results
print(df[["Lab Order ID", "Encounter ID", "Lab Test",
          "Lab Result", "Orphan Lab Result"]].head(10))

print("\nLab results missing a linking ID:", df["Orphan Lab Result"].sum())
print("Lab orders linked to multiple encounters:", len(invalid_orders))
print(invalid_orders)

  Lab Order ID Encounter ID              Lab Test  Lab Result  \
0  LAB-0000001   ENC-000001               Glucose       13.06
1  LAB-0000002   ENC-000002             Potassium       74.27
2  LAB-0000003   ENC-000003           Lipid Panel        9.73
3  LAB-0000004   ENC-000004  COMPLETE BLOOD COUNT       71.42
4  LAB-0000005   ENC-000005                   WBC      114.62
5  LAB-0000006   ENC-000006                   ALT      112.33
6  LAB-0000007   ENC-000007                   AST       57.12
7  LAB-0000008   ENC-000008            Hemoglobin      157.15
8  LAB-0000009   ENC-000009            Creatinine       56.36
9  LAB-0000010   ENC-000010           Lipid Panel      122.13

   Orphan Lab Result
0              False
1              False
2              False
3              False
4              False
5              False
6              False
7              False
8              False
9              False

Lab results missing a linking ID: 0
Lab orders linked to multiple encounters: 0
Series([], Name: Encounter ID, dtype: int64)

In [22]:
#20. Apply role-based masking to notes and remove names, phone numbers, and other direct identifiers.
# Mask clinical notes
df["Clinical Notes"] = "MASKED"

# Remove direct patient identifiers
df = df.drop(
    columns=["Patient ID", "Patient Name", "Phone"],
    errors="ignore"
)

# Display the privacy-safe dataset
print(df.head(10))

# Verify that identifiers have been removed
print("\nRemaining direct identifiers:",
      [col for col in ["Patient ID", "Patient Name", "Phone"]
       if col in df.columns])

  Encounter ID          Facility              Dept                   Arrival  \
0   ENC-000001     WEST HOSPITAL         EMERGENCY 2026-01-25 02:20:00+00:00
1   ENC-000002     EAST HOSPITAL  GENERAL MEDICINE                       NaT
2   ENC-000003     WEST HOSPITAL       ORTHOPEDICS                       NaT
3   ENC-000004  CENTRAL HOSPITAL               ICU                       NaT
4   ENC-000005     EAST HOSPITAL         EMERGENCY                       NaT
5   ENC-000006  CENTRAL HOSPITAL        CARDIOLOGY 2026-08-20 19:42:00+00:00
6   ENC-000007     EAST HOSPITAL       ORTHOPEDICS                       NaT
7   ENC-000008     WEST HOSPITAL        LABORATORY                       NaT
8   ENC-000009     EAST HOSPITAL               ICU                       NaT
9   ENC-000010    NORTH-HOSPITAL               ICU                       NaT

                     Triage                 Discharge       Status Lab Unit  \
0 2026-01-25 03:10:00+00:00 2026-01-25 07:39:00+00:00    COMPLETED      NaN
1                       NaT                       NaT   discharged   mmol/L
2                       NaT                       NaT     admitted    mg/dL
3                       NaT                       NaT      NO-SHOW    mg/dL
4                       NaT                       NaT    COMPLETED      NaN
5 2026-08-20 20:02:00+00:00 2026-08-21 04:36:00+00:00   discharged    MG/DL
6                       NaT                       NaT    CANCELLED      NaN
7                       NaT                       NaT  in progress    MG/DL
8                       NaT                       NaT    CANCELLED    MG/DL
9                       NaT                       NaT    COMPLETED   mmol/l

  Appointment ID      Appointment DateTime  ... Diagnosis Code Issue  \
0    APT-0000001 2026-01-11 11:01:00+00:00  ...                False
1    APT-0000002                       NaT  ...                 True
2    APT-0000003                       NaT  ...                False
3    APT-0000004                       NaT  ...                False
4    APT-0000005                       NaT  ...                False
5    APT-0000006 2026-08-20 05:01:00+00:00  ...                False
6    APT-0000007                       NaT  ...                False
7    APT-0000008                       NaT  ...                False
8    APT-0000009                       NaT  ...                False
9    APT-0000010                       NaT  ...                False

  Procedure Code Issue Bed Information Issue  \
0                 True                 False
1                False                 False
2                False                 False
3                 True                 False
4                False                 False
5                 True                 False
6                False                 False
7                False                 False
8                False                 False
9                False                 False

                                    Timestamp Issue Negative Wait  \
0                                                           False
1  Missing Arrival Missing Triage Missing Discharge         False
2  Missing Arrival Missing Triage Missing Discharge         False
3  Missing Arrival Missing Triage Missing Discharge         False
4  Missing Arrival Missing Triage Missing Discharge         False
5                                                           False
6  Missing Arrival Missing Triage Missing Discharge         False
7  Missing Arrival Missing Triage Missing Discharge         False
8  Missing Arrival Missing Triage Missing Discharge         False
9  Missing Arrival Missing Triage Missing Discharge         False

  Discharge Before Admission Cancelled Encounter Test Record  \
0                      False               False       False
1                      False               False       False
2                      False               False       False
3                      False               False       False
4                      False               False       False
5                      False               False       False
6                      False                True       False
7                      False               False       False
8                      False                True       False
9                      False               False       False

  Include in Operations Orphan Lab Result
0                  True             False
1                  True             False
2                  True             False
3                  True             False
4                  True             False
5                  True             False
6                 False             False
7                  True             False
8                 False             False
9                  True             False

[10 rows x 55 columns]

Remaining direct identifiers: []

In [ ]:
#Standardize text and missing-value placeholders
for col in df.columns:
    if df[col].dtype == "object" or isinstance(df[col].dtype, pd.StringDtype):
        df[col] = df[col].astype("string").str.strip()

        df[col] = df[col].replace({
            "": pd.NA,
            "NOT_APPLICABLE": pd.NA,
            "NOT APPLICABLE": pd.NA,
            "N/A": pd.NA,
            "NULL": pd.NA,
            "null": pd.NA
        })

#Standardize status columns
for col in ["Status", "Appointment Status", "Procedure Status",
            "Lab Result Status", "Medication Administration Status"]:
    if col in df.columns:
        df[col] = df[col].str.upper()

#Check duplicate rows
print("Duplicate rows:", df.duplicated().sum())

#Check duplicate encounter IDs
print("Duplicate Encounter IDs:",
      df["Encounter ID"].duplicated().sum())

#Show remaining missing values
print("\nMissing values by column:")
print(df.isnull().sum()[df.isnull().sum() > 0])

#Show final dataset size
print("\nFinal rows:", len(df))
print("Final columns:", len(df.columns))
print("\nCleaning checks completed.")

Duplicate rows: 0
Duplicate Encounter IDs: 699

Missing values by column:
Arrival                             80000
Triage                              80000
Discharge                           80000
Lab Unit                            12753
Appointment DateTime                80000
Admission                           80000
Transfer                            80000
Procedure DateTime                  80000
Procedure Cancellation Reason       16674
Lab Result Status                   16641
Lab Result DateTime                 80000
Reference Range                     19925
Lab Result Unit                     12753
Medication Administration Status    16770
Dosage Unit                         16603
Bed Inventory Status                16806
Payer                               14336
Staff Shift                         16538
Shift Start                         33430
Shift End                           33253
Timestamp Issue                     20000
dtype: int64

Final rows: 100000
Final columns: 55

Cleaning checks completed.

In [ ]:
#Standardize all column names
df.columns = (
    df.columns.str.strip()
    .str.replace(" ", "_")
    .str.replace(r"[^A-Za-z0-9_]", "", regex=True)
)

#Standardize text values
for col in df.select_dtypes(include=["object", "string"]).columns:
    df[col] = df[col].astype("string").str.strip()

#Standardize status values
status_columns = [
    "Status",
    "Appointment_Status",
    "Procedure_Status",
    "Lab_Result_Status",
    "Medication_Administration_Status"
]

for col in status_columns:
    if col in df.columns:
        df[col] = df[col].str.upper()

# Standardize common status variations
if "Status" in df.columns:
    df["Status"] = df["Status"].replace({
        "COMPLETE": "COMPLETED",
        "CANCELED": "CANCELLED",
        "NO SHOW": "NO-SHOW"
    })

#Convert billing columns to numeric
amount_columns = [
    "Billed_Amount",
    "Paid_Amount",
    "Outstanding_Amount"
]

for col in amount_columns:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors="coerce")

#Flag invalid event sequences
df["Negative_Wait"] = (
    df["Arrival"].notna() &
    df["Triage"].notna() &
    (df["Triage"] < df["Arrival"])
) if "Arrival" in df.columns and "Triage" in df.columns else False

df["Discharge_Before_Admission"] = (
    df["Admission"].notna() &
    df["Discharge"].notna() &
    (df["Discharge"] < df["Admission"])
) if "Admission" in df.columns and "Discharge" in df.columns else False

#Flag billing issues
if all(col in df.columns for col in amount_columns):
    df["Billing_Issue"] = (
        (df["Billed_Amount"] < 0) |
        (df["Paid_Amount"] < 0) |
        (df["Outstanding_Amount"] < 0) |
        (df["Paid_Amount"] > df["Billed_Amount"])
    )
else:
    df["Billing_Issue"] = False

#Create a privacy-safe dataset
df_safe = df.copy()

if "Clinical_Notes" in df_safe.columns:
    df_safe["Clinical_Notes"] = "MASKED"

df_safe = df_safe.drop(
    columns=["Patient_ID", "Patient_Name", "Phone"],
    errors="ignore"
)

#Create exception records
exception_mask = (
    df["Negative_Wait"] |
    df["Discharge_Before_Admission"] |
    df["Billing_Issue"]
)

exceptions = df.loc[exception_mask].copy()

#Save both CSV files
df_safe.to_csv("Hospital_Cleaned_Data.csv", index=False)
exceptions.to_csv("Hospital_Exception_Records.csv", index=False)

#Display final results
print("Cleaning and standardization completed!")
print("Total rows:", len(df_safe))
print("Total columns:", len(df_safe.columns))
print("Exception records:", len(exceptions))
print("Duplicate rows:", df_safe.duplicated().sum())
print("Column names:")
print(df_safe.columns.tolist())

Cleaning and standardization completed!
Total rows: 100000
Total columns: 56
Exception records: 11315
Duplicate rows: 0
Column names:
['Encounter_ID', 'Facility', 'Dept', 'Arrival', 'Triage', 'Discharge', 'Status', 'Lab_Unit', 'Appointment_ID', 'Appointment_DateTime', 'Appointment_Status', 'Ward', 'Specialty', 'Clinician_Role', 'Admission', 'Transfer', 'Procedure_DateTime', 'Procedure_Status', 'Procedure_Cancellation_Reason', 'Lab_Order_ID', 'Lab_Test', 'Specimen_Type', 'Lab_Result', 'Lab_Result_Status', 'Lab_Result_DateTime', 'Reference_Range', 'Lab_Result_Unit', 'Diagnosis_Code', 'Procedure_Code', 'Medication_Administration_Status', 'Dosage_Unit', 'Bed_ID', 'Bed_Inventory_Status', 'Payer', 'Billed_Amount', 'Paid_Amount', 'Outstanding_Amount', 'Staff_Shift', 'Shift_Start', 'Shift_End', 'Severity', 'Priority', 'Clinical_Notes', 'Patient_Key', 'Event_Order_Issue', 'Diagnosis_Code_Issue', 'Procedure_Code_Issue', 'Bed_Information_Issue', 'Timestamp_Issue', 'Negative_Wait', 'Discharge_Before_Admission', 'Cancelled_Encounter', 'Test_Record', 'Include_in_Operations', 'Orphan_Lab_Result', 'Billing_Issue']